Added social networks buttons
3v-workspace/DataOceanLanding pull request #3
Opened 2020-12-29 11:30 UTC by Litsyshyn

https://razom.atlassian.net/browse/DO-855?atlOrigin=eyJpIjoiNDBmZTI3ODZhYWMxNGY0M2FiZTg5OTdkZmRiMmZjZTkiLCJwIjoiaiJ9

2020-12-29 12:10 UTC, Litsyshyn commented
I am not sure about classes, or no.... i am pretty sure that they are wrong or not necessery.

2020-12-29 14:43 UTC, roman-tiukh requested changes
design:
![image](https://user-images.githubusercontent.com/38906004/103291539-ac824b00-49f4-11eb-8282-a521d1844a10.png)
this PR:
![image](https://user-images.githubusercontent.com/38906004/103291580-c4f26580-49f4-11eb-8ca3-81a9a16cf3eb.png)

2020-12-29 14:43 UTC, roman-tiukh commented on index.html
> +                        <img class="footer__item" src="static/img/facebook.svg" class="header__item @media">
`@media`?

2020-12-29 14:43 UTC, roman-tiukh commented on index.html
> +                <ul class="footer__item navigation navigation_align-center navigation_white">
what is class `navigation_align-center`, i cant find this class in css or js files.

`navigation_align-left` same

2020-12-29 14:43 UTC, roman-tiukh commented on index.html
> +                    <a class="navigation__item" href="https://www.facebook.com/DataOceanGroup/" target="_blank">
a child component of `<ul>` element must be `<li>`

2020-12-29 20:01 UTC, Litsyshyn commented on index.html
> +                <ul class="footer__item navigation navigation_align-center navigation_white">
`navigation_align-center`  is a copy\paste from previous. There was `center`  and i thought i can move objects on page, but it's not )

2020-12-29 20:01 UTC, Litsyshyn commented on index.html
> +                        <img class="footer__item" src="static/img/facebook.svg" class="header__item @media">
it is about positions on page, i thought it is about spaces between social networks icons(pics)

2020-12-29 20:05 UTC, roman-tiukh commented on index.html
> +                <ul class="footer__item navigation navigation_align-center navigation_white">
this question also concerns @AlenaYanish

2020-12-29 20:06 UTC, roman-tiukh commented on index.html
> +                    <a class="navigation__item" href="https://www.facebook.com/DataOceanGroup/" target="_blank">
@AlenaYanish

2020-12-29 20:06 UTC, roman-tiukh commented on index.html
> +                        <img class="footer__item" src="static/img/facebook.svg" class="header__item @media">
http://htmlbook.ru/css/value/media

2021-01-02 15:19 UTC, Litsyshyn commented
@roman-tiukh updated.

2021-01-11 08:16 UTC, roman-tiukh requested changes

2021-01-11 08:16 UTC, roman-tiukh commented on index.html
> +                </ul>
```suggestion
                <div class="footer__item">
                        <a href="https://www.facebook.com/DataOceanGroup/" target="_blank">
                            <img class="footer__item" src="static/img/facebook.svg">
                        </a>
                        <a href="https://www.linkedin.com/company/data-ocean/" target="_blank">
                            <img class="footer__item" src="static/img/linkedin.svg">
                        </a>
                        <a href="mailto:info@dataocean.us" target="_blank">
                            <img class="footer__item" src="static/img/email.svg">
                        </a>
                </div>
```

2021-01-11 12:33 UTC, Litsyshyn commented on index.html
> +                </ul>
I'll try to do like this before, but it was'nt work or work incorrect. I dont remember how exactly, but its does'nt.

2021-01-11 15:01 UTC, merged