payments for landing
3v-workspace/DataOceanLanding pull request #6
Opened 2021-01-08 21:48 UTC by Keeslow

do-860

2021-01-11 13:52 UTC, roman-tiukh requested changes
1. Need `en` localization
2. Need getting list of subscriptions(tariff) from backend.
/api/payment/subscriptions/
3. Fonts as in design

2021-01-19 08:53 UTC, roman-tiukh approved these changes

2021-01-19 08:54 UTC, Keeslow reviewed
en localization - done
getting list of subscriptions(tariff) from backend - done
Fonts as in design - done

2021-01-19 10:17 UTC, Keeslow commented
conflict resolved

2021-01-19 12:39 UTC, roman-tiukh approved these changes

2021-01-19 12:39 UTC, merged