DO-955 Add link to header logo
3v-workspace/DataOceanLanding pull request #8
Opened 2021-01-15 22:20 UTC by Litsyshyn

Added redirect to https://dp.dataocean.us/auth/sign-in/ from landing header logo. https://razom.atlassian.net/browse/DO-955
It's not in task, but i guess it must be added also to footer logo.

Upd.
Figured out that reversal logo already available, so delete adde by myself and correct code.

2021-01-18 07:53 UTC, roman-tiukh requested changes

2021-01-18 07:53 UTC, roman-tiukh commented on index.html
> +                <a class="footer__item" href="https://dp.dataocean.us/auth/sign-in/" target="_blank">
Use env variables for generate links

2021-01-18 07:53 UTC, roman-tiukh commented on index.html
> +                <a class="footer__item" href="https://dp.dataocean.us/auth/sign-in/" target="_blank">
DO_FRONTEND_HOST

2021-01-18 12:43 UTC, roman-tiukh requested changes

2021-01-18 12:43 UTC, roman-tiukh commented on index.html
> +                <a class="footer__item" href="https://dp.dataocean.us/auth/sign-in/" target="_blank">
forgot to change here

2021-01-18 12:44 UTC, Litsyshyn commented on index.html
> +                <a class="footer__item" href="https://dp.dataocean.us/auth/sign-in/" target="_blank">
Yes, sorry.

2021-01-19 07:12 UTC, roman-tiukh approved these changes

2021-01-19 07:12 UTC, merged